
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
