
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 8089
      targetPort: 8089
      protocol: TCP
