
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: dev
  labels:
    app: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service
          image: YOUR_AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/shipping-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8088
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8088
            initialDelaySeconds: 60
            periodSeconds: 20
