apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - namespace.yaml
  - services/api-gateway/deployment.yaml
  - services/api-gateway/service.yaml
  - services/auth-service/deployment.yaml
  - services/auth-service/service.yaml
  - services/cart-service/deployment.yaml
  - services/cart-service/service.yaml
  - services/inventory-service/deployment.yaml
  - services/inventory-service/service.yaml
  - services/notification-service/deployment.yaml
  - services/notification-service/service.yaml
  - services/order-service/deployment.yaml
  - services/order-service/service.yaml
  - services/payment-service/deployment.yaml
  - services/payment-service/service.yaml
  - services/product-service/deployment.yaml
  - services/product-service/service.yaml
  - services/shipping-service/deployment.yaml
  - services/shipping-service/service.yaml
  - services/user-service/deployment.yaml
  - services/user-service/service.yaml