
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: dev
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: 028610956643.dkr.ecr.ap-south-1.amazonaws.com/payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 20
