
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8087
      targetPort: 8087
      protocol: TCP
